### ISSUE TITLE
MessageBus decoration policy

### ISSUE THREAD

**Issue by patrykbaszak** [patrykbaszak/messenger-cache-bundle#16]
Solution:

```yaml
messenger_cache:
    pools:
        default: filesystem
        runtime: runtime
        redis: redis
    decorated_message_buses:
        - cachedMessage.bus
    message_bus_decorators:
        '-1': App\MessageBus\LoggingMessageBusDecorator
```

```php
        /** @var string[] $decoratedBuses */
        $decoratedBuses = $container->getParameter('messenger_cache.decorated_message_buses');
        /** @var string[] $messageBusDecorators */
        $messageBusDecorators = $container->getParameter('messenger_cache.message_bus_decorators');
        uksort($messageBusDecorators, function ($a, $b) {
            $a = (int) str_replace('_', '-', (string) $a);
            $b = (int) str_replace('_', '-', (string) $b);

            return $b <=> $a;
        });

        foreach ($decoratedBuses as $bus) {
            $decoratedDefinitionId = $bus.'.decorated';
            $definition = $container->getDefinition($bus);
            $container->setDefinition($decoratedDefinitionId, $definition);
            $i = 0;
            foreach ($messageBusDecorators as $priority => $decorator) {
                $id = $bus.'.decorator_no_'.$i;
                $decorator = $container->register($id, $decorator)
                    ->setArgument('$decorated', $earlierDecorator ?? $definition)
                    ->setAutowired(true)
                    ->setAutoConfigured(true);
                ++$i;
                $earlierDecorator = $decorator;
            }

            $container->setDefinition($bus, $decorator ?? $definition);
```
