### ISSUE TITLE
Bundle shouldn't redeclare default bus

### ISSUE THREAD

**Issue by patrykbaszak** [patrykbaszak/messenger-cache-bundle#17]
This is wrong:
```yaml
# src/Resources/config/packages/messenger.yaml
framework:
    messenger:
        default_bus: messenger.bus.default // it shouldn't be here
        buses:
            messenger.bus.default: // it shouldn't be here
            cachedMessage.bus:
```
