### ISSUE TITLE
MessageBus decoration control

### ISSUE THREAD

**Issue by patrykbaszak** [patrykbaszak/messenger-cache-bundle#7]
[polish]

Dekorator MessageBus'a stosowany przez tę paczkę wymaga stworzenia od razu wielu innych obiektów wymaganych przez system Cache i Symfony Cache. Może się okazać, że będzie to dla kogoś zbyt duży narzut i chciałby móc ręcznie wskazać opcję dekorowania lub nie konkretnego argumentu typu messageBus w projekcie.

```yaml
# config/packages/messenger_cache.yaml
messenger_cache:
    pools:
        # ....
    message_bus_decoration_strategy: all / filtered by attribute / marked with an attribute
```

all:
```php
public function __construct(MessageBus $messageBus) // decorated, attributes are ignored
```

filtered by attribute:
```php
public function __construct(#[IgnoreCacheDecoration] MessageBus $messageBus) // not decorated

public function __construct(MessageBus $messageBus) // decorated and the #[CacheDecoration] attribute is ignored
```

marked with an attribute:
```php
public function __construct(#[CacheDecoration] MessageBus $messageBus) // decorated

public function __construct(MessageBus $messageBus) // not decorated and the #[IgnoreCacheDecoration] attribute is ignored
```

**Comment by patrykbaszak** [comment]
Dodatkowy powód, dla którego chciałbym to zrobić:
Podczas korzystania z tej paczki przy tworzeniu kolejnych bundle'i w zasadzie wymuszamy na czyimś projekcie istnienie dodatkowego dekoratora na MessageBus'ie, co może być totalnie nieoczekiwanym rezultatem.

Dlatego bundle mógłby ustawiać wartość `messenger_cache.message_bus_decoration_strategy: marked with an attribute` i dostawiać atrybut `#[CacheDecoration]` w miejscu wstrzyknięcia MessageBusa co zapobiegłoby zalaniu czyjegoś projektu dekorowaniem MessageBus'a, który w pozostałych miejscach byłby bezużyteczny.

Jednocześnie skorzystanie w projekcie z pozostałych strategii nie wyłączyłoby cache twórcę bundle'a miejscu.

**Comment by patrykbaszak** [comment]
Przyjęta opcja:
```yaml
messenger_cache:
    pools:
        default: filesystem
        runtime: runtime
        redis: redis
    decorated_message_buses:
        - cachedMessage.bus
```
